name: UNLMTD
favicon: null
layout_spectrum: 0.6653805745299906
typography_spectrum: 0.46933101979084313
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.9540297919884324
  lightness: 0.37845324515365064
  saturation: 0.2898880238644779
  rhythmicContrast: 0.8813797426410019
purpose: []
